var aNavItemDate = [
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
			price:'3299元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg23.png',
			name:'小米8青春版',
			price:'3299元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg24.png',
			name:'小米8屏幕指纹版',
			price:'3199元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg25.png',
			name:'小米8',
			price:'2699元起',
		},
		{
			url:'javascript:;',
			img:'image/qg26.png',
			name:'小米8 SE',
			price:'1799元起',
		},
		{
			url:'javascript:;',
			img:'image/qg27.png',
			name:'小米8Max3',
			price:'1699元起',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg28.png',
			name:'红米6Pro',
			price:'999元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg29.png',
			name:'红米6',
			price:'799元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg30.png',
			name:'红米6A',
			price:'799元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg31.png',
			name:'红米Note 5',
			price:'1099元起',
		},
		{
			url:'javascript:;',
			img:'image/qg32.png',
			name:'红米S2',
			price:'999元起',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg33.png',
			name:'小米电视4S 75英寸',
			price:'7999元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg34.png',
			name:'小米电视4A 32英寸',
			price:'899元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg35.png',
			name:'小米电视4A 43英寸青春版',
			price:'1499元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg36.png',
			name:'小米电视4A 50英寸',
			price:'1999元起',
			tag:'热卖'
		},
		{
			url:'javascript:;',
			img:'image/qg37.jpg',
			name:'小米电视4A 55英寸',
			price:'2499元起',
			tag:'热卖'
		},
		{
			url:'javascript:;',
			img:'image/qg38.png',
			name:'查看全部',
			price:'全部电视',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg39.jpg',
			name:'小米笔记本 Air 12.5"',
			price:'3599元起',
		},
		{
			url:'javascript:;',
			img:'image/qg40.jpg',
			name:'小米笔记本 Air 13.3"',
			price:'4599元起',
		},
		{
			url:'javascript:;',
			img:'image/qg41.png',
			name:'小米笔记本 15.6"',
			price:'4199元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg42.png',
			name:'小米笔记本 Pro 15.6"',
			price:'5599元起',
		},
		{
			url:'javascript:;',
			img:'image/qg44.png',
			name:'小米游戏本',
			price:'6699元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg45.png',
			name:'小米平板',
			price:'1099元起',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg46.jpg',
			name:'米家互联网空调',
			price:'1999元起',
			tag:'新品'
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg47.png',
			name:'小米8 青春版',
			price:'1399元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg48.png',
			name:'小米8 屏幕指纹版',
			price:'3199元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg49.jpg',
			name:'小米手环3 NFC版',
			price:'199元起',
		},
		{
			url:'javascript:;',
			img:'image/qg50.jpg',
			name:'小米米家小白智能摄像机增强版',
			price:'399元起',
		},
		{
			url:'javascript:;',
			img:'image/qg51.jpg',
			name:'小米小爱智能闹钟',
			price:'14元起',
		},
		{
			url:'javascript:;',
			img:'image/qg52.png',
			name:'小米小爱蓝牙音箱随身版',
			price:'49元起',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg53.png',
			name:'小米路由器 4',
			price:'179元起',
			tag:'双频双核'
		},
		{
			url:'javascript:;',
			img:'image/qg54.png',
			name:'小米路由器 4Q',
			price:'79元起',
		},
		{
			url:'javascript:;',
			img:'image/qg55.png',
			name:'小米路由器 3A',
			price:'109元起',
		},
		{
			url:'javascript:;',
			img:'image/qg56.png',
			name:'小米路由器 3G',
			price:'189元起',
			tag:'双千兆'
		},
		{
			url:'javascript:;',
			img:'image/qg57.png',
			name:'小米路由器 HD/Pro',
			price:'499元起',
			tag:'大千兆'
		},
		{
			url:'javascript:;',
			img:'image/qg58.png',
			name:'查看全部小米路由器',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg59.jpg',
			name:'米家空气净化器Pro',
			price:'1499元起',
		},
		{
			url:'javascript:;',
			img:'image/qg60.jpg',
			name:'小米净水器',
			price:'1999元起',
		},
		{
			url:'javascript:;',
			img:'image/qg61.jpg',
			name:'米家扫地机器人',
			price:'1699元起',
		},
		{
			url:'javascript:;',
			img:'image/qg62.jpg',
			name:'小米小爱音箱mini',
			price:'169元起',
		},
		{
			url:'javascript:;',
			img:'image/qg63.jpg',
			name:'米家电动剃须刀',
			price:'199元起',
		},
		{
			url:'javascript:;',
			img:'image/qg64.jpg',
			name:'查看全部',
			price:'智能硬件',
		},
	],
];
var aCateItemDate = [
	[
		{
			url:'javascript:;',
			img:'image/zl1.png',
			name:'小米MIX 3',
		},
			{
			url:'javascript:;',
			img:'image/zl2.png',
			name:'小米Max 3',
		},
		{
			url:'javascript:;',
			img:'image/zl3.png',
			name:'红米6A',
		},
		{
			url:'javascript:;',
			img:'image/zl4.png',
			name:'手机上门维修',
		},
		{
			url:'javascript:;',
			img:'image/zl5.png',
			name:'小米8 青春版',
		},
		{
			url:'javascript:;',
			img:'image/zl6.png',
			name:'小米6X',
		},
		{
			url:'javascript:;',
			img:'image/zl7.png',
			name:'红米Note5',
		},
		{
			url:'javascript:;',
			img:'image/zl8.png',
			name:'云服务空间月卡',
		},
		{
			url:'javascript:;',
			img:'image/zl9.png',
			name:'小米8屏幕指纹',
		},
		{
			url:'javascript:;',
			img:'image/zl10.png',
			name:'黑鲨游戏手机',
		},
		{
			url:'javascript:;',
			img:'image/zl12.png',
			name:'红米Note5',
		},
			{
			url:'javascript:;',
			img:'image/zl13.png',
			name:'移动4G + 专区',
		},
		{
			url:'javascript:;',
			img:'image/zl14.png',
			name:'小米8',
		},
		{
			url:'javascript:;',
			img:'image/zl15.png',
			name:'黑鲨游戏手机',
		},
		{
			url:'javascript:;',
			img:'image/zl16.png',
			name:'对比手机',
		},
		{
			url:'javascript:;',
			img:'image/zl17.png',
			name:'小米8 SE',
		},
		{
			url:'javascript:;',
			img:'image/zl18.png',
			name:'红米6 Pro',
		},
		{
			url:'javascript:;',
			img:'image/zl19.png',
			name:'米粉卡 日租卡',
		},
		{
			url:'javascript:;',
			img:'image/zl20.png',
			name:'小米MIX 2S',
		},
		
	],
	[
		{
			url:'javascript:;',
			img:'image/zl21.png',
			name:'米家激光投影电视',
		},
			{
			url:'javascript:;',
			img:'image/zl22.png',
			name:'小米电视4A',
		},
		{
			url:'javascript:;',
			img:'image/zl23.png',
			name:'小米电视4X',
		},
			{
			url:'javascript:;',
			img:'image/zl24.png',
			name:'小米电视4S',
		},

		{
			url:'javascript:;',
			img:'image/zl25.png',
			name:'小米电视4A',
		},
			{
			url:'javascript:;',
			img:'image/zl26.png',
			name:'小米电视4C',
		},

		{
			url:'javascript:;',
			img:'image/zl27.png',
			name:'小米电视',
		},
			{
			url:'javascript:;',
			img:'image/zl28.png',
			name:'小米电视4S',
		},

		{
			url:'javascript:;',
			img:'image/zl29.png',
			name:'小米电视4A',
		},
			{
			url:'javascript:;',
			img:'image/zl31.png',
			name:'小米电视4C',
		},

		{
			url:'javascript:;',
			img:'image/zl32.png',
			name:'小米电视4',
		},
			{
			url:'javascript:;',
			img:'image/zl33.png',
			name:'小米电视4S',
		},

		{
			url:'javascript:;',
			img:'image/zl34.png',
			name:'小米电视4A',
		},
			{
			url:'javascript:;',
			img:'image/zl35.png',
			name:'小米电视4C',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/zl36.png',
			name:'小米笔记本 15.6"',
		},
			{
			url:'javascript:;',
			img:'image/zl37.png',
			name:'鼠标',
		},
		{
			url:'javascript:;',
			img:'image/zl38.png',
			name:'小米笔记本 13.3"',
		},
			{
			url:'javascript:;',
			img:'image/zl40.png',
			name:'转接器',
		},
		{
			url:'javascript:;',
			img:'image/zl41.png',
			name:'小米笔记本 12.5"',
		},
			{
			url:'javascript:;',
			img:'image/zl42.png',
			name:'平板配件',
		},
		{
			url:'javascript:;',
			img:'image/zl43.png',
			name:'小米游戏本',
		},
			{
			url:'javascript:;',
			img:'image/zl44.png',
			name:'笔记本双肩包',
		},
		{
			url:'javascript:;',
			img:'image/zl45.png',
			name:'小米平板4',
		},
		{
			url:'javascript:;',
			img:'image/zl46.png',
			name:'小米内胆包',
		},
		{
			url:'javascript:;',
			img:'image/zl47.png',
			name:'键盘',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/zl47.png',
			name:'米家洗衣机',
		},
		{
			url:'javascript:;',
			img:'image/zl48.png',
			name:'扫地机器人',
		},
		{
			url:'javascript:;',
			img:'image/zl49.png',
			name:'电水壶',
		},
		{
			url:'javascript:;',
			img:'image/zl50.png',
			name:'新风机',
		},
		{
			url:'javascript:;',
			img:'image/zl51.png',
			name:'米家空调',
		},
		{
			url:'javascript:;',
			img:'image/zl52.png',
			name:'扫地机配件',
		},
		{
			url:'javascript:;',
			img:'image/zl53.png',
			name:'滤水壶',
		},
		{
			url:'javascript:;',
			img:'image/zl54.png',
			name:'电暖器',
		},
		{
			url:'javascript:;',
			img:'image/zl55.png',
			name:'米家互联网空调',
		},
		{
			url:'javascript:;',
			img:'image/zl56.png',
			name:'米家空调',
		},
		{
			url:'javascript:;',
			img:'image/zl57.png',
			name:'空气净化器',
		},
		{
			url:'javascript:;',
			img:'image/zl58.png',
			name:'落地风扇',
		},
		{
			url:'javascript:;',
			img:'image/zl59.png',
			name:'米家空调',
		},
		{
			url:'javascript:;',
			img:'image/zl60.png',
			name:'落地风扇',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/zl61.png',
			name:'手环手表',
		},
			{
			url:'javascript:;',
			img:'image/zl62.png',
			name:'平衡车配件',
		},
		{
			url:'javascript:;',
			img:'image/zl63.png',
			name:'VR',
		},
		{
			url:'javascript:;',
			img:'image/zl64.png',
			name:'智能后视镜',
		},
		{
			url:'javascript:;',
			img:'image/zl65.png',
			name:'平衡车',
		},
		{
			url:'javascript:;',
			img:'image/zl66.png',
			name:'车载空气净化器',
		},
		{
			url:'javascript:;',
			img:'image/zl67.png',
			name:'滑板车',
		},
		{
			url:'javascript:;',
			img:'image/zl68.png',
			name:'自行车',
		},
		{
			url:'javascript:;',
			img:'image/zl69.png',
			name:'车载逆变器',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/zl70.png',
			name:'路由器',
		},
			{
			url:'javascript:;',
			img:'image/zl71.png',
			name:'智能门锁',
		},
		{
			url:'javascript:;',
			img:'image/zl72.png',
			name:'对讲机',
		},
			{
			url:'javascript:;',
			img:'image/zl73.png',
			name:'照片打印机',
		},
		{
			url:'javascript:;',
			img:'image/zl74.png',
			name:'智能家庭',
		},
			{
			url:'javascript:;',
			img:'image/zl75.png',
			name:'无人机',
		},
		{
			url:'javascript:;',
			img:'image/zl76.png',
			name:'摄像机',
		},
			{
			url:'javascript:;',
			img:'image/zl77.png',
			name:'照相机',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/zl78.jpg',
			name:'移动电源',
		},
		{
			url:'javascript:;',
			img:'image/zl79.jpg',
			name:'自拍杆',
		},
		{
			url:'javascript:;',
			img:'image/zl80.jpg',
			name:'黑鲨配件',
		},
		{
			url:'javascript:;',
			img:'image/zl81.jpg',
			name:'数据线',
		},
		{
			url:'javascript:;',
			img:'image/zl82.jpg',
			name:'存储卡',
		},
		{
			url:'javascript:;',
			img:'image/zl83.jpg',
			name:'其他配件',
		},
		{
			url:'javascript:;',
			img:'image/zl84.jpg',
			name:'车充',
		},
		{
			url:'javascript:;',
			img:'image/zl85.jpg',
			name:'手机壳',
		},
		{
			url:'javascript:;',
			img:'image/zl86.jpg',
			name:'充电器',
		},
		{
			url:'javascript:;',
			img:'image/zl87.jpg',
			name:'手机贴膜',
		},
		{
			url:'javascript:;',
			img:'image/zl88.jpg',
			name:'无线充',
		},
		{
			url:'javascript:;',
			img:'image/zl89.jpg',
			name:'手机支架',
		},
		{
			url:'javascript:;',
			img:'image/zl90.jpg',
			name:'电池',
		},
		{
			url:'javascript:;',
			img:'image/zl91.jpg',
			name:'平板配件',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/xl1.jpg',
			name:'洗手机',
		},
		{
			url:'javascript:;',
			img:'image/xl2.jpg',
			name:'体温计',
		},
		{
			url:'javascript:;',
			img:'image/xl3.jpg',
			name:'米兔拉杆箱',
		},
		{
			url:'javascript:;',
			img:'image/xl4.jpg',
			name:'剃须刀',
		},
		{
			url:'javascript:;',
			img:'image/xl5.jpg',
			name:'早教启智',
		},
		{
			url:'javascript:;',
			img:'image/xl6.jpg',
			name:'婴儿推车',
		},
		{
			url:'javascript:;',
			img:'image/xl7.jpg',
			name:'牙刷',
		},
		{
			url:'javascript:;',
			img:'image/xl8.jpg',
			name:'遥控电动',
		},
		{
			url:'javascript:;',
			img:'image/xl9.jpg',
			name:'儿童书包',
		},
		{
			url:'javascript:;',
			img:'image/xl10.jpg',
			name:'吹风机',
		},
		{
			url:'javascript:;',
			img:'image/xl11.jpg',
			name:'益智积木',
		},
		{
			url:'javascript:;',
			img:'image/xl12.jpg',
			name:'体重秤',
		},
		{
			url:'javascript:;',
			img:'image/xl13.jpg',
			name:'儿童手表',
		},
		{
			url:'javascript:;',
			img:'image/xl14.jpg',
			name:'血压计',
		},
		{
			url:'javascript:;',
			img:'image/xl15.jpg',
			name:'儿童滑板车',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/xl16.jpg',
			name:'小米小爱音箱mini',
		},
		{
			url:'javascript:;',
			img:'image/xl17.jpg',
			name:'小米AI音箱',
		},
		{
			url:'javascript:;',
			img:'image/xl18.jpg',
			name:'线控耳机',
		},
		{
			url:'javascript:;',
			img:'image/xl19.jpg',
			name:'蓝牙耳机K歌',
		},
		{
			url:'javascript:;',
			img:'image/xl20.jpg',
			name:'蓝牙耳机',
		},
		{
			url:'javascript:;',
			img:'image/xl21.jpg',
			name:'头戴耳机',
		},
		{
			url:'javascript:;',
			img:'image/xl22.jpg',
			name:'品牌耳机',
		},
		{
			url:'javascript:;',
			img:'image/xl23.jpg',
			name:'蓝牙音箱',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/xl24.jpg',
			name:'双肩包',
		},
		{
			url:'javascript:;',
			img:'image/xl25.jpg',
			name:'眼镜',
		},
		{
			url:'javascript:;',
			img:'image/xl26.jpg',
			name:'保温杯',
		},
		{
			url:'javascript:;',
			img:'image/xl27.jpg',
			name:'签字笔',
		},
		{
			url:'javascript:;',
			img:'image/xl28.jpg',
			name:'钱包',
		},
		{
			url:'javascript:;',
			img:'image/xl29.jpg',
			name:'床垫',
		},
		{
			url:'javascript:;',
			img:'image/xl30.jpg',
			name:'伞',
		},
		{
			url:'javascript:;',
			img:'image/xl31.jpg',
			name:'笔记本',
		},
		{
			url:'javascript:;',
			img:'image/xl32.jpg',
			name:'收纳包',
		},
		{
			url:'javascript:;',
			img:'image/xl33.jpg',
			name:'枕头',
		},
		{
			url:'javascript:;',
			img:'image/xl34.jpg',
			name:'驱蚊器',
		},
		{
			url:'javascript:;',
			img:'image/xl35.jpg',
			name:'旅行箱',
		},
		{
			url:'javascript:;',
			img:'image/xl36.jpg',
			name:'沙发',
		},
		{
			url:'javascript:;',
			img:'image/xl37.jpg',
			name:'尤克里里',
		},
		{
			url:'javascript:;',
			img:'image/xl38.jpg',
			name:'运动鞋',
		},
		{
			url:'javascript:;',
			img:'image/xl39.jpg',
			name:'饰品',
		},
		{
			url:'javascript:;',
			img:'image/xl40.jpg',
			name:'毛巾/浴巾',
		},
		{
			url:'javascript:;',
			img:'image/xl41.jpg',
			name:'服饰',
		},
		{
			url:'javascript:;',
			img:'image/xl42.jpg',
			name:'螺丝刀',
		},
		{
			url:'javascript:;',
			img:'image/xl43.jpg',
			name:'米兔',
		},
	]
]
var aElecItemData = [
	[
		{
			url:'javascript:;',
			img:'image/elsc1.jpg',
			name:'小米电视4A 43英寸青春版',
			desc:'全高清屏/人工智能语音',
			price:'1499',
			del:'1699元',
			flag:{
				name:'off-flog',
				content:'减200元'
			},
			view:{
			recommend:'直都想买个小米电视，果然不失望，大爱',
			author:'来自于1471474629的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc2.jpg',
			name:'小米电视4C 50英寸',
			desc:'4K HDR/人工智能语音',
			price:'1999',
			del:'2199元',
			flag:{
				name:'off-flog',
				content:'减200元'
			},
			view:{
			recommend:'我一直催货，还不给我发货，我等了一周，买了为了看NBA',
			author:'来自于的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc3.png',
			name:'15.6 笔记本 i5 4G MX110',
			desc:'全面均衡的国民轻薄本',
			price:'4199',
			del:'',
			flag:{
				name:'off-flog',
				content:'新品'
			},
			view:{
			recommend:'拿包裹的心事迫切的，用的都是小米的，自己送给',
			author:'来自于大婷宝的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc4.jpg',
			name:'小米笔记本Air 13.3″',
			desc:'小米笔记本Pro 15.6"',
			price:'5399',
			del:'',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'召唤神龙',
			author:'来自于1450685747的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc5.png',
			name:'米家空气净化器Pro',
			desc:'米家空气净化器 2S ',
			price:'1499',
			del:'',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'卧室里的净化器好小，这次买个大的放到客厅里，我米加油',
			author:'来自于孔繁义的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc6.jpg',
			name:'米家电水壶',
			desc:'一杯水，是一家人的安心 ',
			price:'99',
			del:'',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'外形时尚，容量大，好打理，再也不用担心清理问题，这',
			author:'来自于精益眼镜的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc7.png',
			name:'米家LED吸顶灯',
			desc:'色温亮度可调',
			price:'399',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'不错 方便好用 调光温馨 有调光 锁定功能',
			author:'来自于千龙的评价'
			}
		},
		{
			top:{
				url:'javascript:;',
				img:'image/elsc8.jpg',
				name:'小米净水器',
				price:'1899'
			},
			bottom:{
				url:'javascript:;',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	],
	[
		{
			url:'javascript:;',
			img:'image/elsc9.jpg',
			name:'小米电视4X 43英寸',
			desc:'',
			price:'1399',
			del:'1599元',
			flag:{
				name:'off-flog',
				content:'新品'
			},
			view:{
			recommend:'一直用小米，电视都两台了',
			author:'来自于小林的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc10.jpg',
			name:'小米电视4 55英寸',
			desc:'4.9mm 极超薄高端旗舰电视',
			price:'3699',
			del:'3999元',
			flag:{
				name:'off-flog',
				content:'减300元'
			},
			view:{
			recommend:'很惊艳，全家人都很喜欢，感觉有点买小了！效果也不错',
			author:'来自妳狠重要的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc11.jpg',
			name:'小米电视4A 32英寸',
			desc:'64位四核处理器',
			price:'799',
			del:'999元',
			flag:{
				name:'off-flog',
				content:'减300元'
			},
			view:{
			recommend:'非常不错，一直信赖小米',
			author:'来自于小米Max的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc12.jpg',
			name:'小米电视4C 50英寸',
			desc:'4K HDR 人工智能语音电视"',
			price:'1899',
			del:'2199元',
			flag:{
				name:'off-flog',
				content:'减300元'
			},
			view:{
			recommend:'朋友同事来家都说电视超值，非常棒',
			author:'来自于BI4JEO的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc13.jpg',
			name:'小米电视4A 58英寸',
			desc:'老人小孩都会用的人工智能语音电视',
			price:'2499',
			del:'2999元',
			flag:{
				name:'off-flog',
				content:'新品'
			},
			view:{
			recommend:'相信小米，支持小米……',
			author:'来自于BI4JEO的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc14.jpg',
			name:'小米电视4 65英寸',
			desc:'全面屏人工智能语音电视',
			price:'5999',
			del:'',
			flag:{
				name:'off-flog',
				content:'新品'
			},
			view:{
			recommend:'不错的选择 小米加油小米加油',
			author:'1423466332'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc15.jpg',
			name:'小米盒子3 增强版',
			desc:'高端 4K 网络机顶盒',
			price:'399',
			del:'449元',
			flag:{
				name:'off-flog',
				content:'减50元'
			},
			view:{
			recommend:'收到，神速耶！谢谢！',
			author:'来自于李强的评价'
			}
		},
		{
			top:{
				url:'javascript:;',
				img:'image/elsc16.jpg',
				name:'小米盒子3s',
				price:'299'
			},
			bottom:{
				url:'javascript:;',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	],
	[
		{
			url:'javascript:;',
			img:'image/elsc17.jpg',
			name:'',
			desc:'更强悍的专业笔记本',
			price:'6299',
			// del:'1699元',
			// flag:{
			// 	name:'off-flog',
			// 	content:'减200元'
			// },
			view:{
			recommend:'外形非常漂亮 开机速度也很快',
			author:'来自于2173319198的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc18.jpg',
			name:'',
			desc:'全新升级：第八代四核处理器',
			price:'5399',
			// del:'2199元',
			// flag:{
			// 	name:'off-flog',
			// 	content:'减200元'
			// },
			view:{
			recommend:'还不错，开机速度棒棒声！',
			author:'来自张剑虹的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc19.jpg',
			name:'小米游戏本',
			desc:'',
			price:'6699',
			del:'',
			flag:{
				name:'off-flog',
				content:'新品'
			},
			view:{
			recommend:'16日10点下单，今天15点收到',
			author:'来自于楼春雨的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc20.jpg',
			name:'小米笔记本Air 13.3″',
			desc:'',
			price:'5399',
			del:'',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'小米笔记本外观真的太漂亮了!屏幕清晰',
			author:'来自于时代----年华的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc21.jpg',
			name:'小米无线鼠标',
			desc:'把舒服握在手里',
			price:'69',
			del:'',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'还没开始用 摸着手感不错 ',
			author:'来自于1479537340的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc22.jpg',
			name:'小米便携鼠标',
			desc:'轻薄便携，含电池仅重 77.5g',
			price:'99',
			del:'',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'鼠标质感很棒，性价比超高，好评好评。',
			author:'来自于Amian的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc23.jpg',
			name:'悦米机械键盘',
			desc:'87 键|铝合金机身|TTC 红轴',
			price:'289',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'有了键盘我居然吃鸡了 键盘Very nice',
			author:'来自于.u的评价'
			}
		},
		{
			top:{
				url:'javascript:;',
				img:'image/elsc24.jpg',
				name:'多功能转接器',
				price:'149'
			},
			bottom:{
				url:'javascript:;',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	],
	[
		{
			url:'javascript:;',
			img:'image/elsc25.jpg',
			name:'米家恒温电水壶',
			desc:'一杯水的温度，刚刚好',
			price:'199',
			del:'',
			// flag:{
			// 	name:'off-flog',
			// 	content:'减200元'
			// },
			view:{
			recommend:'四月份米粉节买的电热水壶',
			author:'来自于汝州长途客运的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc26.jpg',
			name:'小米随身手电筒',
			desc:'1 挡调光，随心而亮',
			price:'799',
			del:'',
			flag:{
				name:'off-flog',
				content:'新品'
			},
			view:{
			recommend:'小米手电好 我的家乡更美',
			author:'来自于期待中的鱼的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc27.jpg',
			name:'米家扫地机器人',
			desc:'智能路径规划|大风压澎湃吸力',
			price:'1699',
			del:'',
			// flag:{
			// 	name:'off-flog',
			// 	content:'新品'
			// },
			view:{
			recommend:'拿包裹的心事迫切的，用的都是小米的，自己送给',
			author:'来自于大婷宝的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc28.jpg',
			name:'小米米家空气净化器 2S',
			desc:'OLED 显示屏/激光颗粒物传感器',
			price:'899',
			del:'',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'放在女儿房间。很安静。',
			author:'来自于漫步者的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc30.jpg',
			name:'米家压力IH电饭煲',
			desc:'智能烹饪|压力 IH 加热',
			price:'999',
			del:'',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'煮饭香喷喷，米妹子快来开饭了！',
			author:'来自于朒朒鳥飝的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc29.jpg',
			name:'飞利浦智睿球泡灯',
			desc:'自由调节亮度及色温 / 传统白炽灯外形',
			price:'49',
			del:'',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'灯泡很棒，手机操作很方便',
			author:'来自于精益眼镜的评价'
			}
		},
		{
			url:'javascript:;',
			img:'image/elsc31.jpg',
			name:'米家 LED 智能台灯',
			desc:'无可视频闪|亮度色温无级调节',
			price:'169',
			// flag:{
			// 	name:'off-flog',
			// 	content:'jian800'
			// },
			view:{
			recommend:'拿到手上比较厚实，挺沉的。',
			author:'来自于1451143140的评价'
			}
		},
		{
			top:{
				url:'javascript:;',
				img:'image/elsc32.jpg',
				name:'智能 LED',
				price:'379'
			},
			bottom:{
				url:'javascript:;',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	],
]