var aNavItemDate = [
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
			price:'3299元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg23.png',
			name:'小米8青春版',
			price:'3299元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg24.png',
			name:'小米8屏幕指纹版',
			price:'3199元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg25.png',
			name:'小米8',
			price:'2699元起',
		},
		{
			url:'javascript:;',
			img:'image/qg26.png',
			name:'小米8 SE',
			price:'1799元起',
		},
		{
			url:'javascript:;',
			img:'image/qg27.png',
			name:'小米8Max3',
			price:'1699元起',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg28.png',
			name:'红米6Pro',
			price:'999元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg29.png',
			name:'红米6',
			price:'799元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg30.png',
			name:'红米6A',
			price:'799元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg31.png',
			name:'红米Note 5',
			price:'1099元起',
		},
		{
			url:'javascript:;',
			img:'image/qg32.png',
			name:'红米S2',
			price:'999元起',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg33.png',
			name:'小米电视4S 75英寸',
			price:'7999元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg34.png',
			name:'小米电视4A 32英寸',
			price:'899元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg35.png',
			name:'小米电视4A 43英寸青春版',
			price:'1499元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg36.png',
			name:'小米电视4A 50英寸',
			price:'1999元起',
			tag:'热卖'
		},
		{
			url:'javascript:;',
			img:'image/qg37.jpg',
			name:'小米电视4A 55英寸',
			price:'2499元起',
			tag:'热卖'
		},
		{
			url:'javascript:;',
			img:'image/qg38.png',
			name:'查看全部',
			price:'全部电视',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg39.jpg',
			name:'小米笔记本 Air 12.5"',
			price:'3599元起',
		},
		{
			url:'javascript:;',
			img:'image/qg40.jpg',
			name:'小米笔记本 Air 13.3"',
			price:'4599元起',
		},
		{
			url:'javascript:;',
			img:'image/qg41.png',
			name:'小米笔记本 15.6"',
			price:'4199元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg42.png',
			name:'小米笔记本 Pro 15.6"',
			price:'5599元起',
		},
		{
			url:'javascript:;',
			img:'image/qg44.png',
			name:'小米游戏本',
			price:'6699元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg45.png',
			name:'小米平板',
			price:'1099元起',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg46.jpg',
			name:'米家互联网空调',
			price:'1999元起',
			tag:'新品'
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg47.png',
			name:'小米8 青春版',
			price:'1399元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg48.png',
			name:'小米8 屏幕指纹版',
			price:'3199元起',
			tag:'新品'
		},
		{
			url:'javascript:;',
			img:'image/qg49.jpg',
			name:'小米手环3 NFC版',
			price:'199元起',
		},
		{
			url:'javascript:;',
			img:'image/qg50.jpg',
			name:'小米米家小白智能摄像机增强版',
			price:'399元起',
		},
		{
			url:'javascript:;',
			img:'image/qg51.jpg',
			name:'小米小爱智能闹钟',
			price:'14元起',
		},
		{
			url:'javascript:;',
			img:'image/qg52.png',
			name:'小米小爱蓝牙音箱随身版',
			price:'49元起',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg53.png',
			name:'小米路由器 4',
			price:'179元起',
			tag:'双频双核'
		},
		{
			url:'javascript:;',
			img:'image/qg54.png',
			name:'小米路由器 4Q',
			price:'79元起',
		},
		{
			url:'javascript:;',
			img:'image/qg55.png',
			name:'小米路由器 3A',
			price:'109元起',
		},
		{
			url:'javascript:;',
			img:'image/qg56.png',
			name:'小米路由器 3G',
			price:'189元起',
			tag:'双千兆'
		},
		{
			url:'javascript:;',
			img:'image/qg57.png',
			name:'小米路由器 HD/Pro',
			price:'499元起',
			tag:'大千兆'
		},
		{
			url:'javascript:;',
			img:'image/qg58.png',
			name:'查看全部小米路由器',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg59.jpg',
			name:'米家空气净化器Pro',
			price:'1499元起',
		},
		{
			url:'javascript:;',
			img:'image/qg60.jpg',
			name:'小米净水器',
			price:'1999元起',
		},
		{
			url:'javascript:;',
			img:'image/qg61.jpg',
			name:'米家扫地机器人',
			price:'1699元起',
		},
		{
			url:'javascript:;',
			img:'image/qg62.jpg',
			name:'小米小爱音箱mini',
			price:'169元起',
		},
		{
			url:'javascript:;',
			img:'image/qg63.jpg',
			name:'米家电动剃须刀',
			price:'199元起',
		},
		{
			url:'javascript:;',
			img:'image/qg64.jpg',
			name:'查看全部',
			price:'智能硬件',
		},
	],
]

var aCateItemDate = [
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX 3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米Max 3',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'红米6A',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'手机上门维修',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米8 青春版',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米6X',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'红米Note5',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'云服务空间月卡',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米8屏幕指纹',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'黑鲨游戏手机',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'红米Note5',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'移动4G + 专区',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米8',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'黑鲨游戏手机',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'对比手机',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米8 SE',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'红米6 Pro',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'米粉卡 日租卡',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX 2S',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'红米6',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米移动 电话卡',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
			{
			url:'javascript:;',
			img:'image/qg22.png',
			name:'小米MIX3',
		},
	],
];

var aElecItemData = [
	[
		{
			url:'javascript:;',
			img:'image/qg1.png',
			name:'15.6 Pro i5 8G',
			desc:'更强悍的专业笔记本',
			price:'5999.00',
			del:'6299元',
			flog:'提醒我',
			people:'已有121人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg2.png',
			name:'小米6X 6GB+64GB樱花粉',
			desc:'更轻薄美观的拍照手机',
			price:'1399.00',
			del:'1799元',
			flog:'提醒我',
			people:'已有160人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg3.png',
			name:'新小米移动电源2',
			desc:'双向快充，铝合金外壳',
			price:'1.00',
			del:'79元',
			flog:'提醒我',
			people:'已有17913人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg4.png',
			name:'小米运动蓝牙耳机青春版',
			desc:'音随你动',
			price:'1.00',
			del:'99元',
			flog:'提醒我',
			people:'已有16441人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg5.png',
			name:'小米 USB type',
			desc:'快充快传 闪速高效',
			price:'1.00',
			del:'14.9元',
			flog:'提醒我',
			people:'已有7010人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg6.png',
			name:'90分简约头层小牛皮手包',
			desc:'进口头层牛皮革 精致油边工艺',
			price:'99.50',
			del:'199元',
			flog:'提醒我',
			people:'已有648人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg7.png',
			name:'小米6X 6GB+64GB 赤焰红',
			desc:'轻薄美观的拍照手机/前置2000万',
			price:'1399.00',
			del:'1799元',
			flog:'提醒我',
			people:'已有103人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg8.png',
			name:'小米8 青春版 6GB+64GB',
			desc:'潮流镜面渐变色，自拍旗舰',
			price:'1599.00',
			del:'1699元',
			flog:'提醒我',
			people:'已有88人开启提醒',
		},

		{
			url:'javascript:;',
			img:'image/qg9.png',
			name:'小米8 SE 6GB+128GB',
			desc:'三星 AMOLED 全面屏 小屏旗舰',
			price:'1949.00',
			del:'2299元',
			flog:'提醒我',
			people:'已有39人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg10.png',
			name:'小米8 SE 6GB+128GB',
			desc:'三星 AMOLED 全面屏 小屏旗舰',
			price:'1949.00',
			del:'2299元',
			flog:'提醒我',
			people:'已有38人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg11.png',
			name:'15.66"笔记本 i5 8G MX110',
			desc:'全面均衡的国民轻薄本',
			price:'4299.00',
			del:'4499元',
			flog:'提醒我',
			people:'已有43人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg12.png',
			name:'小米笔记本Pro 15 i5 8G',
			desc:'更强悍的专业笔记本',
			price:'5399.00',
			del:'5599元',
			flog:'提醒我',
			people:'已有26人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg13.png',
			name:'小米游戏本15.6 8代i7 8G',
			desc:'冷酷的性能怪兽',
			price:'7299.00',
			del:'7499元',
			flog:'提醒我',
			people:'已有25人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg14.png',
			name:'小米游戏本15.6 8代i5 8G',
			desc:'L冷酷的性能怪兽',
			price:'6499.00',
			del:'6699元',
			flog:'提醒我',
			people:'已有33人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg15.png',
			name:'悦米机械键盘 白色',
			desc:'U轻松输入，手感出众',
			price:'269.00',
			del:'289元',
			flog:'提醒我',
			people:'已有25人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg16.png',
			name:'小米手环3腕带 深空蓝',
			desc:'顺化柔软，触感舒适',
			price:'3699.00',
			del:'4699元',
			flog:'提醒我',
			people:'已有36人开启提醒',
		},

	],
	[
		{
			url:'javascript:;',
			img:'image/sg1.jpg',
			name:'星座S925银镶珍珠吊坠',
			desc:'巨蟹座',
			price:'179.00',
			del:'199元',
			flog:'提醒我',
			people:'已有53人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/sg2.jpg',
			name:'星座S925银镶珍珠吊坠',
			desc:'狮子座',
			price:'179.00',
			del:'199元',
			flog:'提醒我',
			people:'已有103人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/sg3.jpg',
			name:'保温杯 白色',
			desc:'12小时保温保冷',
			price:'89.00',
			del:'99元',
			flog:'提醒我',
			people:'已有153人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/sg4.jpg',
			name:'小米蓝牙耳机',
			desc:'6.5克轻巧',
			price:'1.00',
			del:'539元',
			flog:'提醒我',
			people:'已有10355人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/sg5.jpg',
			name:'星座S925银镶珍珠吊坠',
			desc:'天蝎座',
			price:'179.00',
			del:'199元',
			flog:'提醒我',
			people:'已有53人开启提醒',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg1.png',
			name:'15.6 Pro i5 8G',
			desc:'更强悍的专业笔记本',
			price:'5999.00',
			del:'6299元',
			flog:'提醒我',
			people:'已有121人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg1.png',
			name:'15.6 Pro i5 8G',
			desc:'更强悍的专业笔记本',
			price:'5999.00',
			del:'6299元',
			flog:'提醒我',
			people:'已有121人开启提醒',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg1.png',
			name:'15.6 Pro i5 8G',
			desc:'更强悍的专业笔记本',
			price:'5999.00',
			del:'6299元',
			flog:'提醒我',
			people:'已有121人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg1.png',
			name:'15.6 Pro i5 8G',
			desc:'更强悍的专业笔记本',
			price:'5999.00',
			del:'6299元',
			flog:'提醒我',
			people:'已有121人开启提醒',
		},
	],
	[
		{
			url:'javascript:;',
			img:'image/qg1.png',
			name:'15.6 Pro i5 8G',
			desc:'更强悍的专业笔记本',
			price:'5999.00',
			del:'6299元',
			flog:'提醒我',
			people:'已有121人开启提醒',
		},
		{
			url:'javascript:;',
			img:'image/qg2.png',
			name:'15.6 Pro i5 8G',
			desc:'更强悍的专业笔记本',
			price:'5999.00',
			del:'6299元',
			flog:'提醒我',
			people:'已有121人开启提醒',
		},
	],
]